[tool.poetry]
name = "python-project-50-test"
version = "0.1.0"
description = ""
authors = ["SVI <Svinovoch@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
